### ISSUE TITLE
Adding New Page throws InvalidArgumentException

### ISSUE THREAD

**Issue by webstractions** [lara-press/larapress#17]
I have a fresh install and was looking around the backend and setting things up. Went to add a New Page and received this error:

```
 InvalidArgumentException
The "C:\xampp\htdocs\sites\larapress\resources\views/templates" directory does not exist.
```
I traced this back in the stack to `app\Providers\TemplateAndSidebarServiceProvider.php` on line 56.

```
    protected function getTemplateOptions()
    {
        /** @var FileViewFinder $viewFinder */
        $viewFinder = $this->app['view.finder'];
 
        $templates = [];
        foreach ($viewFinder->getPaths() as $path) {
56:         $possibleTemplates = $viewFinder->getFilesystem()->files($path . '/templates');
 
            foreach ($possibleTemplates as $template) {
                $templates[basename($template, '.blade.php')] =
                    ucwords(str_replace('-', ' ', basename($template, '.blade.php')));
            }
        }
 
        return $templates;
    }
```

The `$path .'/templates'` part is wrong. It should just be `$path`, which points to the root at `resources\views`. Unless of course, there is something missing from this directory that you need a templates folder?

**Comment by jeffberry** [comment]
Hey there,

Thanks for checking our project out! We mainly use this for internal development at our shop - so  forgive us for the lack of public documentation, but please feel free to use it and contribute!

If you create a `templates` folder in `views` does the error go away? What this feature does is scan a folder called `resources/views/templates` and makes any blade files located within there available as template options when creating a new WP page. You can think of it as doing the same thing as how Wordpress picks up page layouts out of a theme folder that have the comment `/* Template Name: ... */` in there and provides those as template options.

**Comment by jeffberry** [comment]
Please also check out our docs: https://github.com/lara-press/docs, we've tried to keep this as accurate as possible.

**Comment by webstractions** [comment]
@jeffberry Yep. Adding the folder in `views` cleared that up. 

I see you already merged a fix. Pretty quick! 

I saw the docs. That's what got me this far, lol. I pretty much understood the nuts and bolts, and just tinkering around with things.

**Comment by skylerfenn** [comment]
Thanks for sharing what you found! I'm going to close this issue since we've resolved things.
